const $=s=>document.querySelector(s);let state=window.APP_STATE, mode='video',activeModule=1,activeLesson=null,currentQuiz=[],currentQuestion=0;
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
function openModal(id,m){if(m)mode=m;$('#'+id).classList.add('open');if(id==='modulesModal')renderModules();if(id==='shopModal')renderShop()}
function closeModal(id){$('#'+id).classList.remove('open')};window.addEventListener('click',e=>{if(e.target.classList.contains('backdrop'))e.target.classList.remove('open')});
function post(data){const token=document.querySelector('meta[name=csrf-token]')?.content||'';return fetch('../back-end/aprendizado_api.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/x-www-form-urlencoded','X-CSRF-Token':token},body:new URLSearchParams({...data,csrf_token:token})}).then(async r=>{const d=await r.json().catch(()=>({ok:false,message:'Resposta inválida do servidor.'}));if(!r.ok&& !d.message)d.message='Não foi possível concluir a operação.';return d})}
function toast(t,good=true){const x=$('#toast');x.textContent=t;x.style.borderColor=good?'#55e4ff88':'#ff82b0';x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3200)}
function localDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function renderState(s){state=s;$('#xp').textContent=s.xp;$('#coins').textContent=s.coins;$('#shopCoins').textContent=s.coins;$('#rankName').textContent=s.rank.name;$('#arenaUserName').textContent=s.userName;$('#arenaAvatar').textContent=s.initials;$('#rankName').style.color=s.rank.color;$('#withinPercent').textContent=s.withinPercent+'%';$('#rankProgress').style.width=s.withinPercent+'%';$('#totalPercent').textContent=s.totalPercent+'%';$('#totalFill').style.width=s.totalPercent+'%';$('#level').textContent=String(s.rank.index+1).padStart(2,'0');$('#streak').textContent=s.streak;$('#bestStreak').textContent=s.bestStreak;$('#freezeCount').textContent=s.freezeCount;$('#nextXp').textContent=s.next?s.next.min+' XP':'MAX';$('#nextRank').textContent=s.next?s.next.name:'—';$('#rankMessage').textContent=s.rank.name==='ESMERALDA'?'Você alcançou o nível máximo!':s.withinPercent>=75?'A próxima patente está perto!':'Continue avançando na sua jornada.';const btn=$('#checkinBtn');const checkedToday=s.lastCheckin===localDate();const canCheckin=Boolean(s.canCheckin);btn.disabled=checkedToday||!canCheckin;btn.title=!canCheckin?'Conclua uma videoaula ou um exercício primeiro.':'';btn.innerHTML=checkedToday?'FOGUINHO ACESO ✓':!canCheckin?'CONCLUA UMA MISSÃO PRIMEIRO':'ACENDER FOGUINHO <span>→</span>';renderActivities(s.activities)}
function renderActivities(a){$('#activityList').innerHTML=a.length?a.map(x=>`<div class="activity-item"><div><b>${esc(x.label)}</b><small>${new Date(x.created_at).toLocaleString('pt-BR')} · +${x.xp} XP · +${x.coins} AFDIS</small></div></div>`).join(''):'<div class="empty">✦ Complete uma aula ou exercício para registrar sua evolução.</div>'}
function checkin(){post({action:'checkin'}).then(d=>{toast(d.message,d.ok);renderState(d.state);if(d.ok)flame()})}
function flame(){const f=$('.flame');f.animate([{transform:'scale(1)'},{transform:'scale(1.25) rotate(-5deg)'},{transform:'scale(1)'}],{duration:700})}
function renderModules(){ $('#trailEyebrow').textContent=mode==='video'?'TRILHA DE VÍDEO':'PRÁTICA GUIADA';$('#trailTitle').textContent=mode==='video'?'Módulos de videoaulas':'Módulos de exercícios';$('#moduleList').innerHTML=state.modules.map(m=>`<button class="module-card ${m.id===activeModule?'active':''}" onclick="selectModule(${m.id})"><small>MÓDULO ${String(m.position).padStart(2,'0')}</small><h3>${esc(m.title)}</h3><p>${m.lesson_count} aulas · ${esc(m.subtitle)}</p></button>`).join('');selectModule(activeModule)}
function selectModule(id){activeModule=id;document.querySelectorAll('.module-card').forEach(x=>x.classList.remove('active'));const rows=state.lessons.filter(l=>Number(l.module_id)===id);$('#lessonList').innerHTML=rows.map((l,i)=>{const completed=Number(mode==='video'?l.lesson_done:l.exercise_done);return `<div class="lesson-row"><span class="num">${String(i+1).padStart(2,'0')}</span><h4>${esc(l.title)}<small>${esc(l.duration)} · ${mode==='video'?'Videoaula':'Exercício correspondente'}</small></h4><button class="lesson-btn ${completed?'done':''}" onclick="openLesson(${l.id})">${completed?'✓ CONCLUÍDA':mode==='video'?'ASSISTIR':'PRATICAR'}</button></div>`}).join('')}
function openLesson(id){activeLesson=state.lessons.find(l=>Number(l.id)===id);$('#lessonTitle').textContent=activeLesson.title;$('#lessonModule').textContent=activeLesson.module_title+' · '+activeLesson.duration;$('#exerciseBox').classList.add('hidden');$('#lessonComplete').classList.toggle('hidden',mode!=='video'||Number(activeLesson.lesson_done));$('#lessonComplete').onclick=()=>completeLesson(id);$('#lessonModal').classList.toggle('exercise-mode',mode==='exercise');$('#commentsPanel').style.display=mode==='video'?'flex':'none';if(mode==='video')loadComments(id);if(mode==='exercise')renderExercise(id);openModal('lessonModal')}
function renderExercise(id){post({action:'get_exercise',lesson_id:id}).then(d=>{if(!d.ok){toast(d.message,false);return}currentQuiz=d.exercise;currentQuestion=0;$('#exerciseBox').classList.remove('hidden');$('#lessonComplete').classList.add('hidden');renderQuestion()})}
function renderQuestion(){const e=currentQuiz[currentQuestion],box=$('#exerciseBox');box.innerHTML=`<h3>Questão ${currentQuestion+1} de ${currentQuiz.length}</h3><div class="quiz-question"><b>${esc(e.question)}</b><div class="exercise-options">${e.options.map((o,i)=>`<button class="exercise-option" onclick="chooseOption(this,${i})">${esc(o)}</button>`).join('')}</div></div><button class="primary exercise-submit" onclick="nextQuestion()">${currentQuestion===currentQuiz.length-1?'FINALIZAR QUIZ':'PRÓXIMA QUESTÃO'} <span>→</span></button>`}
function nextQuestion(){const selected=$('.exercise-option.selected');if(!selected){toast('Escolha uma alternativa para avançar.',false);return}currentQuiz[currentQuestion].selected=Number(selected.dataset.choice);if(currentQuestion<currentQuiz.length-1){currentQuestion++;renderQuestion()}else submitExercise(activeLesson.id)}
function chooseOption(el,i){el.parentElement.querySelectorAll('.exercise-option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');el.dataset.choice=i}
function submitExercise(id){const answers=currentQuiz.map(q=>q.selected);post({action:'complete_exercise',lesson_id:id,answers:JSON.stringify(answers)}).then(d=>{toast(d.ok?`Quiz concluído: ${d.score}/${d.total} · +${d.xpGain} XP`:d.message,d.ok);if(d.ok){renderState(d.state);closeModal('lessonModal');renderModules();if(d.streakActivated)flame()}})}
function completeLesson(id){post({action:'complete_lesson',lesson_id:id}).then(d=>{toast(d.ok?`Aula concluída! +${d.xpGain} XP${d.streakActivated?' · foguinho aceso':''}`:d.message,d.ok);if(d.ok){renderState(d.state);closeModal('lessonModal');renderModules();if(d.streakActivated)flame();if(d.rain)moneyRain()}})}
function renderShop(){const active=state.active;$('#shopGrid').innerHTML=Object.entries(window.ITEMS).map(([id,it])=>{const a=active.includes(id),freeze=id==='streak_freeze';return `<div class="shop-item ${a?'active':''}"><div class="shop-item-top"><span class="item-icon">${esc(it.icon)}</span><span class="item-price">${Number(it.price)} AFDIS</span></div><h3>${esc(it.name)}</h3><p>${esc(it.detail)}</p><button class="buy" ${a||state.coins<it.price?'disabled':''} onclick="buyItem('${id}')">${a?'✓ ATIVO':state.coins<it.price?'SALDO INSUFICIENTE':freeze?'ADQUIRIR CONGELADOR':'ATIVAR VANTAGEM'}</button></div>`}).join('')}
function buyItem(id){post({action:'buy',item:id}).then(d=>{toast(d.message,d.ok);if(d.ok){renderState(d.state);renderShop()}})}
function loadComments(lessonId){post({action:'get_comments',lesson_id:lessonId}).then(d=>{if(d.ok)renderComments(d.comments)})}
function renderComments(comments){const list=$('#commentList');if(!list)return;$('#commentCount').textContent=comments.length;list.innerHTML=comments.map(c=>`<div class="comment"><div><b>${esc(c.author)}</b><span>${esc(c.body)}</span></div><div class="comment-votes"><button class="${Number(c.my_vote)===1?'voted':''}" onclick="voteComment(${c.id},1)">▲ ${c.likes}</button><button class="${Number(c.my_vote)===-1?'voted-down':''}" onclick="voteComment(${c.id},-1)">▼ ${c.dislikes}</button></div></div>`).join('')||'<small>Nenhum comentário nesta aula.</small>'}
function sendComment(e){e.preventDefault();const input=$('#commentInput'),text=input.value.trim();if(!text)return;post({action:'comment',lesson_id:activeLesson.id,text}).then(d=>{input.value='';if(d.ok)renderComments(d.comments)})}
function voteComment(id,vote){post({action:'vote_comment',comment_id:id,vote}).then(()=>loadComments(activeLesson.id))}
function moneyRain(){if(typeof confetti==='function')confetti({particleCount:100,spread:80,origin:{y:.7},colors:['#ffd878','#55e4ff','#b89bff']})}
function resetProgress(){if(confirm('Reiniciar apenas seu progresso de aprendizado?'))post({action:'reset'}).then(d=>{toast(d.message,d.ok);if(d.ok)location.reload()})}
renderState(state);
