(() => {
  'use strict';
  function initBannerEditor() {
    const input = document.getElementById('banner'), modal = document.getElementById('bannerModal'), canvas = document.getElementById('bannerCanvas'), stage = document.getElementById('bannerStage'), preview = document.getElementById('bannerPreview'), zoom = document.getElementById('bannerZoom'), zoomValue = document.getElementById('bannerZoomValue'), output = document.getElementById('bannerCortado'), form = input?.form;
    if (!input || !modal || !canvas || !stage || !preview || !zoom || !zoomValue || !output || !form) return;
    const ctx = canvas.getContext('2d', { alpha: false }); if (!ctx) return; ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = 'high';
    const image = new Image(); let loaded = false, drag = null, offsetX = 0, offsetY = 0;
    const w = () => canvas.width, h = () => canvas.height;
    const metrics = () => { const factor = Number(zoom.value) / 100, contain = Math.min(w() / image.naturalWidth, h() / image.naturalHeight); return { dw: image.naturalWidth * contain * factor, dh: image.naturalHeight * contain * factor }; };
    const clamp = () => { const { dw, dh } = metrics(); const minX = Math.min(0, w() - dw), maxX = Math.max(0, w() - dw), minY = Math.min(0, h() - dh), maxY = Math.max(0, h() - dh); offsetX = Math.min(maxX, Math.max(minX, offsetX)); offsetY = Math.min(maxY, Math.max(minY, offsetY)); if (dw <= w()) offsetX = (w() - dw) / 2; if (dh <= h()) offsetY = (h() - dh) / 2; };
    const draw = () => { if (!loaded) return; const { dw, dh } = metrics(); if (!drag) { offsetX = (w() - dw) / 2; offsetY = (h() - dh) / 2; } clamp(); ctx.fillStyle = '#020b14'; ctx.fillRect(0, 0, w(), h()); const cover = Math.max(w() / image.naturalWidth, h() / image.naturalHeight), bw = image.naturalWidth * cover, bh = image.naturalHeight * cover; ctx.save(); ctx.globalAlpha = .34; ctx.filter = 'blur(18px)'; ctx.drawImage(image, (w() - bw) / 2, (h() - bh) / 2, bw, bh); ctx.restore(); ctx.fillStyle = 'rgba(2,11,20,.22)'; ctx.fillRect(0, 0, w(), h()); ctx.drawImage(image, offsetX, offsetY, dw, dh); zoomValue.textContent = `${zoom.value}%`; preview.src = canvas.toDataURL('image/jpeg', .95); };
    const close = (clear = true) => { modal.hidden = true; modal.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; drag = null; if (clear) input.value = ''; };
    const open = file => { if (!file || (!/^image\/(jpeg|png|webp)$/i.test(file.type) && !/\.(jpe?g|png|webp)$/i.test(file.name))) { alert('Use JPG, PNG ou WEBP no banner.'); input.value = ''; return; } if (file.size > 8 * 1024 * 1024) { alert('O banner deve ter no máximo 8 MB.'); input.value = ''; return; } const reader = new FileReader(); reader.onerror = () => alert('Não foi possível ler o banner.'); reader.onload = () => { image.onload = () => { loaded = true; zoom.value = '50'; drag = null; draw(); modal.hidden = false; modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; }; image.src = String(reader.result); }; reader.readAsDataURL(file); };
    input.addEventListener('change', () => { if (input.files?.[0]) open(input.files[0]); }); zoom.addEventListener('input', () => { drag = null; draw(); }); stage.addEventListener('pointerdown', e => { if (!loaded) return; stage.setPointerCapture?.(e.pointerId); drag = { x: e.clientX, y: e.clientY, ox: offsetX, oy: offsetY }; }); stage.addEventListener('pointermove', e => { if (!drag) return; offsetX = drag.ox + e.clientX - drag.x; offsetY = drag.oy + e.clientY - drag.y; clamp(); draw(); }); stage.addEventListener('pointerup', () => { drag = null; }); stage.addEventListener('pointercancel', () => { drag = null; });
    document.getElementById('bannerClose')?.addEventListener('click', () => close()); document.getElementById('bannerCancel')?.addEventListener('click', () => close()); modal.addEventListener('click', e => { if (e.target === modal) close(); }); document.getElementById('bannerApply')?.addEventListener('click', () => { if (!loaded) return; output.value = canvas.toDataURL('image/jpeg', .95); form.submit(); }); document.addEventListener('keydown', e => { if (e.key === 'Escape' && !modal.hidden) close(); }); window.__bannerEditorReady = true;
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', initBannerEditor, { once: true }); else initBannerEditor();
})();
